### ISSUE TITLE
chunk upload is not working

### ISSUE THREAD

**Issue by alykhan2212** [rahulhaque/laravel-filepond#10]
chunk upload isn't working. Is it possible now to upload large files in chunks using this package ?

**Comment by rahulhaque** [comment]
@alykhan2212 not implemented yet.

**Comment by takielias** [comment]
> @alykhan2212 not implemented yet.

Do you have a plan to implement chunk upload?

**Comment by rahulhaque** [comment]
@takielias @alykhan2212 Of course. However I am not getting much free time to invest in this project. Currently I am focusing on third party storage support which has many workarounds. Choosing one is difficult because there are numerous ways of doing things with Filepond. That's why I have exposed the API for the package. Chunk upload maybe next as I am currently not handling large file uploads for my projects but seems more important than 3rd party storage support. Whichever the case, the next release may contain significant changes.

**Comment by Vikaschapter** [comment]
there is a problem
 with the remove image in this package

**Comment by rahulhaque** [comment]
@Vikaschapter please, elaborate.
